// <auto-generated />
namespace SocialEngineeringExercise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 增加測試資料 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(增加測試資料));
        
        string IMigrationMetadata.Id
        {
            get { return "201610031015148_增加測試資料"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
